// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Persistance;

namespace Payment.Persistance.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20200630150703_LoggingInitial")]
    partial class LoggingInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Payment.Domain.StageLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("EventTasksPlanId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FunctionToCall")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FunctionToRestore")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Input")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Output")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProcessState")
                        .HasColumnType("int");

                    b.Property<bool>("ShouldWaitForPreviousStageToComplete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EventTasksPlanId");

                    b.ToTable("StageLog");
                });

            modelBuilder.Entity("Payment.Domain.TaskDeploymentLogEntry", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompleteByUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventTasksPlanId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("LockedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProcessState")
                        .HasColumnType("int");

                    b.Property<int>("UnderlyingEntityId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("EventTasksPlanId");

                    b.ToTable("LogEntryOfDeploymentPlanExecution");
                });

            modelBuilder.Entity("Payment.Services.DeploymentPlans.EventTasksPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("EventTasksPlan");
                });

            modelBuilder.Entity("Payment.Domain.StageLog", b =>
                {
                    b.HasOne("Payment.Services.DeploymentPlans.EventTasksPlan", null)
                        .WithMany("EventTaskStages")
                        .HasForeignKey("EventTasksPlanId");
                });

            modelBuilder.Entity("Payment.Domain.TaskDeploymentLogEntry", b =>
                {
                    b.HasOne("Payment.Services.DeploymentPlans.EventTasksPlan", "EventTasksPlan")
                        .WithMany()
                        .HasForeignKey("EventTasksPlanId");
                });
#pragma warning restore 612, 618
        }
    }
}
