// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Persistance;

namespace Payment.Persistance.Migrations
{
    [DbContext(typeof(OrderPaymentDbContext))]
    [Migration("20200629132630_OrderPaymentInitial")]
    partial class OrderPaymentInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Payment.Domain.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Canceled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ClientsId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Customerconfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EndHour")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Masterconfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("PaymentsId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonDeclined")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("ServicesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartHour")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UnpayedOrderExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientsId");

                    b.HasIndex("PaymentsId");

                    b.HasIndex("ServicesId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Payment.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PaymentMadeDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Payment.Domain.Order", b =>
                {
                    b.HasOne("Payment.Domain.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentsId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
